### ISSUE TITLE
Mr X wants to know his tickets

### ISSUE THREAD

**Issue by sharma-rishabh** [step-8/scotland-yard-byomkesh#45]
As Mr X
I want to see how many black tickets and 2x cards I have 
So that I know all possible ways to escape

**Acceptance Criteria**

- [x] Criteria 1
  
  - Given I am a player
  - When I am in game page
  - Then I should see how many black and 2x tickets left to Mr. X

**Comment by lakshmiprasannaG** [comment]
Will be covered in #82
