### ISSUE TITLE
Modify the way of highlighting stops

### ISSUE THREAD

**Issue by lakshmiprasannaG** [step-8/scotland-yard-byomkesh#73]
As a user, 
I want to see available stops clearly visible
So that I can decide where to go

- [x] Criteria 1
     -  As a player 
     -  When it is my turn 
     - Then my location pointer should be highlighted

- [x] Criteria 2
    - As a player 
    - When it is my turn 
    - Then I should able to see the possible stops with some animation
    
- [x] Criteria 3
   - As a player and it is my turn 
   - When I click on highlighted stop
   - Then I should see the selected stop with some animation

**Comment by ankammaraod** [comment]
Make sure all the animation should not affect the  existing functionality and
animations should be presize
